Repository rsksmart/rskj, pull requests merged in 2018-02, with the labels that each got.

#407 RFS-55 improve blockchain block locator and RFS-90 call bridge from contract
  rskj-core/src/main/java/co/rsk/peg/Bridge.java
  rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
  rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/DevNetConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/FallbackMainNetConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/RegTestConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetAfterBridgeSyncConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetBeforeBridgeSyncConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetFirstForkConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetAfterBridgeSyncConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetBeforeBridgeSyncConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetFirstForkConfig.java
  rskj-core/src/main/java/org/ethereum/config/net/MainNetConfig.java
  rskj-core/src/main/java/org/ethereum/config/net/TestNetConfig.java
  rskj-core/src/main/java/org/ethereum/vm/program/Program.java
  rskj-core/src/test/java/co/rsk/peg/BridgeFromVMTest.java
  rskj-core/src/test/java/co/rsk/peg/BridgeSupportTest.java
  rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
  rskj-core/src/test/java/co/rsk/peg/performance/BtcBlockchainTest.java
Labels: hard-fork

#479 Fix BlockInfo serialization
  rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java
Labels: bug, core

#475 [RFS-94] Remove bridge method get state for debugging
  rskj-core/src/main/java/co/rsk/peg/Bridge.java
  rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/DevNetConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/RegTestConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetFirstForkConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetFirstForkConfig.java
  rskj-core/src/test/java/co/rsk/peg/BridgeTest.java
  rskj-core/src/test/java/co/rsk/peg/RskForksBridgeTest.java
Labels: federation 💫, network-upgrade 🌱

#480 [RFS-50] Add support for returnDataSize, returnDataCopy and extCodeSize for precompiled contracts
  rskj-core/src/main/java/org/ethereum/config/BlockchainConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/AbstractConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/DevNetConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/RegTestConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/mainnet/MainNetFirstForkConfig.java
  rskj-core/src/main/java/org/ethereum/config/blockchain/testnet/TestNetFirstForkConfig.java
  rskj-core/src/main/java/org/ethereum/vm/VM.java
  rskj-core/src/main/java/org/ethereum/vm/program/Program.java
  rskj-core/src/test/java/co/rsk/util/TestContract.java
  rskj-core/src/test/java/org/ethereum/vm/ProgramTest.java
Labels: federation 💫, network-upgrade 🌱

#493 Tool for migrating configurations between versions
  rskj-core/src/main/java/co/rsk/cli/CliArgsParser.java
  rskj-core/src/main/java/co/rsk/cli/OptionalizableArgument.java
  rskj-core/src/main/java/co/rsk/cli/config/MigrationTool.java
  rskj-core/src/main/java/co/rsk/cli/config/Migrator.java
  rskj-core/src/main/java/co/rsk/cli/config/MigratorConfiguration.java
  rskj-core/src/test/java/co/rsk/cli/config/MigratorTest.java
Labels: enhancement
