Repository rsksmart/rskj, pull requests merged in 2020-08, with the labels that each got.

#1266 Resend transactions fix and refactor
  rskj-core/src/main/java/co/rsk/RskContext.java
  rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java
  rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
  rskj-core/src/main/java/co/rsk/net/TransactionGateway.java
  rskj-core/src/main/java/co/rsk/net/TransactionNodeInformation.java
  rskj-core/src/main/java/co/rsk/net/messages/MessageVisitor.java
  rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionBase.java
  rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionDisabled.java
  rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModuleTransactionInstant.java
  rskj-core/src/main/java/org/ethereum/core/TransactionPool.java
  rskj-core/src/main/java/org/ethereum/core/TransactionPoolAddResult.java
  rskj-core/src/main/java/org/ethereum/facade/EthereumImpl.java
  rskj-core/src/main/java/org/ethereum/net/server/ChannelManager.java
  rskj-core/src/main/java/org/ethereum/net/server/ChannelManagerImpl.java
  rskj-core/src/test/java/co/rsk/core/bc/TransactionPoolImplTest.java
  rskj-core/src/test/java/co/rsk/mine/TransactionModuleTest.java
  rskj-core/src/test/java/co/rsk/net/NodeMessageHandlerTest.java
  rskj-core/src/test/java/co/rsk/net/TransactionGatewayTest.java
  rskj-core/src/test/java/co/rsk/net/TransactionNodeInformationTest.java
  rskj-core/src/test/java/co/rsk/net/messages/MessageVisitorTest.java
  rskj-core/src/test/java/co/rsk/net/utils/TransactionUtils.java
  rskj-core/src/test/java/org/ethereum/net/server/ChannelManagerImplTest.java
  rskj-core/src/test/java/org/ethereum/rpc/Simples/SimpleChannelManager.java
  rskj-core/src/test/java/org/ethereum/rpc/Web3ImplTest.java
Labels: core :atom_symbol:, enhancement, refactor

#1288 Add thread names & mdc to log
  rskj-core/src/main/java/co/rsk/Start.java
  rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java
  rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java
  rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java
  rskj-core/src/main/resources/logback.xml
  rskj-core/src/test/resources/logback.xml
Labels: enhancement

#1285 ForkDetectionData retrieval performance
  rskj-core/src/main/java/co/rsk/util/ListArrayUtil.java
  rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java
  rskj-core/src/main/java/org/ethereum/core/BlockHeader.java
  rskj-core/src/test/java/co/rsk/core/BlockHeaderTest.java
  rskj-core/src/test/java/co/rsk/util/ListArrayUtilTest.java
Labels: mining :pick:, performance

#1284 Fix JSON RPC trace_transaction and trace_block
  rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java
  rskj-core/src/main/java/co/rsk/remasc/RemascFeesPayer.java
  rskj-core/src/main/java/co/rsk/rpc/modules/trace/CallType.java
  rskj-core/src/main/java/co/rsk/rpc/modules/trace/ProgramSubtrace.java
  rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceAction.java
  rskj-core/src/main/java/co/rsk/rpc/modules/trace/TraceTransformer.java
  rskj-core/src/main/java/org/ethereum/vm/program/Program.java
  rskj-core/src/test/java/co/rsk/rpc/modules/trace/TraceModuleImplTest.java
  rskj-core/src/test/java/co/rsk/rpc/modules/trace/TraceTransformerTest.java
  rskj-core/src/test/java/co/rsk/test/dsl/WorldDslProcessor.java
  rskj-core/src/test/java/co/rsk/test/dsltest/WorldDslProcessorTest.java
  rskj-core/src/test/resources/dsl/call01.txt
  rskj-core/src/test/resources/dsl/create201.txt
  rskj-core/src/test/resources/dsl/delegatecall01.txt
Labels: bug, compatibility
